---
name: CI

on:
  pull_request:

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run chktex
        run: |
          sudo apt-get update
          sudo apt-get install -y chktex
          chktex -q -n 6 *.tex

  build-test:
    needs: lint
    name: Build Documents
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate PDF document
        uses: hspaans/latexmk-action@v1
        with:
          format: pdf
          filename: article.tex

      - name: Generate PDF document
        uses: hspaans/latexmk-action@v1
        with:
          format: pdf
          filename: book.tex

      - name: Generate PDF document
        uses: hspaans/latexmk-action@v1
        with:
          format: pdf
          filename: presentation.tex

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documents
          path: '*pdf'
