---
name: CI

on:
  pull_request:

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v4.8.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JSCPD: false
          VALIDATE_GITHUB_ACTIONS: false

  build-test:
    needs: lint
    name: Build Documents
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate PDF document
        uses: hspaans/latexmk-action@v1.1.1
        with:
          format: pdf
          filename: article.tex

      - name: Generate PDF document
        uses: hspaans/latexmk-action@v1.1.1
        with:
          format: pdf
          filename: book.tex

      - name: Generate PDF document
        uses: hspaans/latexmk-action@v1.1.1
        with:
          format: pdf
          filename: presentation.tex

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: documents
          path: '*pdf'
