---
name: CI

on:
  pull_request:

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_ENV: true
          VALIDATE_JSON: true
          VALIDATE_LATEX: true
          VALIDATE_MARKDOWN: true
          VALIDATE_XML: true
          VALIDATE_YAML: true

  build-test:
    needs: lint
    name: Build Documents
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate PDF document
        uses: hspaans/latexmk-action@v1.1.2
        with:
          format: pdf
          filename: article.tex

      - name: Generate PDF document
        uses: hspaans/latexmk-action@v1.1.2
        with:
          format: pdf
          filename: book.tex

      - name: Generate PDF document
        uses: hspaans/latexmk-action@v1.1.2
        with:
          format: pdf
          filename: presentation.tex

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: documents
          path: '*pdf'
